# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df59d2173f427e94d6f381176df84448bb12188c0624b350bc54e2a2cc6c4c1825ff1e0fb98beecd0d58eb41dfc28dd92aa4256ceedac3dfd22de3d593ef0cf

test:
  secret_key_base: fa2776331884962f6d98db3f48711280194096173d20454181e7520a88620f21145a196c41e8644159a1cbf5e48efc76bda96e4a57eb00a0132b19e11aaaa2b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
